"""
Bundle src/ into a single submission.py for Kaggle submission.

Reads every module listed in SRC_FILES in dependency order, strips relative
imports (from .module import ...) and deduplicates kaggle_environments imports
into a single block at the top. The kaggle_environments package is installed
in the Kaggle runtime but must still be imported explicitly.
"""

import re
from pathlib import Path

HEADER = "# Orbit Wars submission — generated by build.py\n\n"

SRC_FILES = [
    Path("src/math_utils.py"),
    Path("src/config.py"),
    Path("src/lookahead.py"),
    Path("src/comets.py"),
    Path("src/endgame.py"),
    Path("src/strategy.py"),
    Path("src/agent.py"),
]

# Matches a full multi-line `from .something import (...)` or single-line form.
RELATIVE_IMPORT_RE = re.compile(
    r"from \.[^\s]+\s+import\s*\([^)]*\)\s*\n|"
    r"^\s*from \.[^\s]+ import [^\n]+\n?",
    re.MULTILINE | re.DOTALL,
)

# Matches a full multi-line `from kaggle_environments... import (\n  ...\n)` block.
KAGGLE_IMPORT_RE = re.compile(
    r"from kaggle_environments[^\n]*import\s*\([^)]*\)\s*\n|"
    r"from kaggle_environments[^\n]*import[^\n]*\n",
    re.DOTALL,
)

KAGGLE_IMPORTS_BLOCK = (
    "from kaggle_environments.envs.orbit_wars.orbit_wars import (\n"
    "    CENTER,\n"
    "    ROTATION_RADIUS_LIMIT,\n"
    "    SUN_RADIUS,\n"
    "    Fleet,\n"
    "    Planet,\n"
    ")\n"
)


def strip_imports(source: str) -> str:
    source = RELATIVE_IMPORT_RE.sub("", source)
    source = KAGGLE_IMPORT_RE.sub("", source)
    return source


def build() -> Path:
    """Bundle src/ into submission.py and return the written path."""
    chunks = [HEADER, KAGGLE_IMPORTS_BLOCK, "\n"]
    for path in SRC_FILES:
        source = path.read_text()
        cleaned = strip_imports(source)
        chunks.append(f"# --- {path} ---\n")
        chunks.append(cleaned.strip() + "\n\n")

    output = Path("submission.py")
    output.write_text("".join(chunks))
    return output


if __name__ == "__main__":
    output = build()
    print(f"Written {output} ({output.stat().st_size} bytes)")

    # Quick sanity check
    content = output.read_text()
    assert "def agent(" in content, "submission.py is missing agent() function!"
    print("OK: agent() function found in submission.py")
