"""
Bundle src/ into a single submission.py for Kaggle submission.

Reads every module listed in SRC_FILES in dependency order, strips relative
imports (from .module import ...) and deduplicates kaggle_environments imports
into a single block at the top. The kaggle_environments package is installed
in the Kaggle runtime but must still be imported explicitly.
"""

import re
from pathlib import Path

HEADER = "# Orbit Wars submission — generated by build.py\n\n"

SRC_FILES = [
    Path("src/math_utils.py"),
    Path("src/config.py"),
    Path("src/lookahead.py"),
    Path("src/comets.py"),
    Path("src/endgame.py"),
    Path("src/strategy.py"),
    Path("src/agent.py"),
]

# Matches a full multi-line `from .something import (...)` or single-line form.
RELATIVE_IMPORT_RE = re.compile(
    r"from \.[^\s]+\s+import\s*\([^)]*\)\s*\n|"
    r"^\s*from \.[^\s]+ import [^\n]+\n?",
    re.MULTILINE | re.DOTALL,
)

# Matches a full multi-line `from kaggle_environments... import (\n  ...\n)` block.
KAGGLE_IMPORT_RE = re.compile(
    r"from kaggle_environments[^\n]*import\s*\([^)]*\)\s*\n|"
    r"from kaggle_environments[^\n]*import[^\n]*\n",
    re.DOTALL,
)

# Matches top-level `import X` and `from X import Y` lines (non-relative, non-kaggle).
# Applied after KAGGLE_IMPORT_RE so `^from \w` cannot accidentally match kaggle lines.
STDLIB_IMPORT_RE = re.compile(
    r"^import \w[^\n]*\n?|^from \w[^\n]*\n?",
    re.MULTILINE,
)

KAGGLE_IMPORTS_BLOCK = (
    "from kaggle_environments.envs.orbit_wars.orbit_wars import (\n"
    "    CENTER,\n"
    "    ROTATION_RADIUS_LIMIT,\n"
    "    SUN_RADIUS,\n"
    "    Fleet,\n"
    "    Planet,\n"
    ")\n"
)


def strip_imports(source: str) -> str:
    source = RELATIVE_IMPORT_RE.sub("", source)
    source = KAGGLE_IMPORT_RE.sub("", source)
    source = STDLIB_IMPORT_RE.sub("", source)
    return source


def build() -> Path:
    """Bundle src/ into submission.py and return the written path."""
    seen: set[str] = set()
    stdlib_imports: list[str] = []
    module_chunks: list[str] = []

    for path in SRC_FILES:
        source = path.read_text()
        # Strip relative and kaggle first so STDLIB_IMPORT_RE cannot see kaggle lines.
        partial = KAGGLE_IMPORT_RE.sub("", RELATIVE_IMPORT_RE.sub("", source))
        for match in STDLIB_IMPORT_RE.finditer(partial):
            line = match.group().rstrip("\n")
            if line not in seen:
                seen.add(line)
                stdlib_imports.append(line)
        module_chunks.append(f"# --- {path} ---\n")
        module_chunks.append(strip_imports(source).strip() + "\n\n")

    chunks = [HEADER, KAGGLE_IMPORTS_BLOCK]
    if stdlib_imports:
        chunks.append("\n".join(stdlib_imports) + "\n")
    chunks.append("\n")
    chunks.extend(module_chunks)

    output = Path("submission.py")
    output.write_text("".join(chunks))
    return output


if __name__ == "__main__":
    output = build()
    print(f"Written {output} ({output.stat().st_size} bytes)")

    # Quick sanity check
    content = output.read_text()
    assert "def agent(" in content, "submission.py is missing agent() function!"
    print("OK: agent() function found in submission.py")
