# Orbit Wars submission — generated by build.py

from kaggle_environments.envs.orbit_wars.orbit_wars import (
    CENTER,
    ROTATION_RADIUS_LIMIT,
    SUN_RADIUS,
    Fleet,
    Planet,
)
import math
from dataclasses import dataclass
from collections import namedtuple

# --- src/math_utils.py ---
# Board edges, mirroring the engine's authoritative BOARD_SIZE (= 100.0). Kept
# as literals rather than importing BOARD_SIZE so build.py's flat bundle needs
# no extra kaggle symbol; test_board_bounds_match_engine_board_size pins them to
# the engine value so they can't silently drift. Used for off-board bound checks
# (e.g. comet intercept).
BOARD_MIN = 0.0
BOARD_MAX = 100.0

_LOG_1000 = math.log(1000.0)


def orbital_radius(planet: Planet) -> float:
    """Distance from the planet to the sun at the center (50, 50)."""
    dx = planet.x - CENTER
    dy = planet.y - CENTER
    return math.sqrt(dx * dx + dy * dy)


def _is_stationary_radius(radius: float) -> bool:
    """The static-planet rule, over an already-computed orbital radius.

    The single source of truth for the boundary. Callers that already hold the
    radius (predict_planet_position needs it for the orbital math regardless)
    use this directly rather than recomputing it via is_stationary.
    """
    return radius + SUN_RADIUS >= ROTATION_RADIUS_LIMIT


def is_stationary(planet: Planet) -> bool:
    """True if the planet sits outside the rotation limit and never moves."""
    return _is_stationary_radius(orbital_radius(planet))


def predict_planet_position(
    planet: Planet, angular_velocity: float, turns: int
) -> tuple[float, float]:
    """
    Predict where a planet will be after `turns` turns.

    Orbiting planets rotate around the sun at (50, 50) with a constant
    angular_velocity (radians/turn). Static planets (orbital_radius + SUN_RADIUS >=
    ROTATION_RADIUS_LIMIT, the same boundary as is_stationary) don't move —
    return current position unchanged. A zero angular_velocity likewise means
    no movement.

    Matches the engine formula (orbit_wars.py:586):
        angle = initial_angle + angular_velocity * step
    cos/sin periodicity handles large horizons naturally — no modulo needed.
    """
    radius = orbital_radius(planet)
    if _is_stationary_radius(radius) or angular_velocity == 0:
        return (planet.x, planet.y)
    current_angle = math.atan2(planet.y - CENTER, planet.x - CENTER)
    future_angle = current_angle + angular_velocity * turns
    return (
        CENTER + radius * math.cos(future_angle),
        CENTER + radius * math.sin(future_angle),
    )


def angle_to_target(
    from_x: float, from_y: float, target_x: float, target_y: float
) -> float:
    """
    Return the angle in radians from (from_x, from_y) toward (target_x, target_y).

    Kaggle's coordinate system: origin top-left, y increases downward.
    The action format uses standard math angles (0 = right, pi/2 = down).
    """
    return math.atan2(target_y - from_y, target_x - from_x)


def distance(x1: float, y1: float, x2: float, y2: float) -> float:
    return math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)


def is_enemy(owner: int, player: int) -> bool:
    """True for any non-neutral, non-player owner (neutral == -1)."""
    return owner not in (-1, player)


def sum_owned(units, player: int, attr: str = "ships", enemy: bool = False) -> int:
    """Sum `attr` over units owned by `player`, or by any enemy when enemy=True.

    `units` is any planet or fleet sequence — both expose `.owner`, `.ships`, and
    (planets only) `.production`. Kept a thin generator-sum with no per-call setup:
    score_state calls it four times per simulated state inside the lookahead hot
    loop, which runs across every self-play game.
    """
    if enemy:
        return sum(getattr(u, attr) for u in units if is_enemy(u.owner, player))
    return sum(getattr(u, attr) for u in units if u.owner == player)


def fleet_speed(num_ships: int, max_speed: float = 6.0) -> float:
    """Fleet speed on the logarithmic curve from the spec, clamped to max_speed.

    Mirrors the engine (orbit_wars.py:521-529): the log curve is capped with
    min(speed, max_speed) so large fleets never drift above the engine's speed.
    """
    if num_ships <= 1:
        return 1.0
    speed = 1.0 + (max_speed - 1.0) * (math.log(num_ships) / _LOG_1000) ** 1.5
    return min(speed, max_speed)


def _min_dist_pt_to_segment(
    px: float, py: float,
    sx1: float, sy1: float, sx2: float, sy2: float,
) -> float:
    """Minimum distance from point (px, py) to segment (sx1,sy1)→(sx2,sy2)."""
    dx = sx2 - sx1
    dy = sy2 - sy1
    d_len_sq = dx * dx + dy * dy
    if d_len_sq == 0:
        return math.sqrt((px - sx1) ** 2 + (py - sy1) ** 2)
    t = max(0.0, min(1.0, ((px - sx1) * dx + (py - sy1) * dy) / d_len_sq))
    cx = sx1 + t * dx
    cy = sy1 + t * dy
    return math.sqrt((px - cx) ** 2 + (py - cy) ** 2)


def path_crosses_sun(x1: float, y1: float, x2: float, y2: float) -> bool:
    """True if the segment from (x1,y1) to (x2,y2) passes within SUN_RADIUS of CENTER."""
    return _min_dist_pt_to_segment(CENTER, CENTER, x1, y1, x2, y2) < SUN_RADIUS


def turns_to_arrive(
    from_x: float, from_y: float, target_x: float, target_y: float, num_ships: int
) -> int:
    """Estimate turns for a fleet to reach a target using current positions."""
    d = distance(from_x, from_y, target_x, target_y)
    speed = fleet_speed(num_ships)
    return max(1, math.ceil(d / speed))

# --- src/config.py ---
PARAMS = {
    # Own planet classification
    "fortress_min_ships": 31,
    "fortress_min_production": 2,
    "factory_min_production": 5,
    "stationary_value_bonus": 0,
    # Threat level ratios
    "weak_ratio": 1.9947103092400609,
    "contested_ratio": 1.3116870693167089,
    # Send fractions (flattened from nested dict)
    "frac_fortress_easy_neutral":    0.6373798481888991,
    "frac_fortress_hard_neutral":    0.8280958418348433,
    "frac_fortress_soft_enemy":      0.7693872378844533,
    "frac_fortress_contested_enemy": 0.8513568427887089,
    "frac_fortress_hardened_enemy":  0.6205349006008141,
    "frac_factory_easy_neutral":     0.7918877418991281,
    "frac_factory_soft_enemy":       0.5716368569289937,
    "frac_outpost_easy_neutral":     0.6091691624282816,
    "frac_outpost_soft_enemy":       0.5040091397305635,
    # Defense
    "threat_radius": 7.361366948460609,
    "threat_eta_window": 15,
    "defense_reinforce_fraction": 0.3476899630999006,
    # NOTE: inbound fleets are now aggregated per planet, so this multiplies the
    # *combined* incoming ships, not a single fleet's. This value was tuned against
    # the old per-fleet behavior — do NOT promote until re-tuned. See CLAUDE.md
    # "Pending re-tune: multi-fleet defense aggregation" (rm trials/study.db →
    # run_trials.py → copy winners here → build.py).
    "defense_incoming_multiplier": 0.6176537815824305,
    "eta_buffer": 8,
    "min_garrison": 26,
    # Aggression scaling
    "aggression_max": 0.9797831434048456,
    "aggression_min": 0.4881980293792295,
    "game_length": 500,
    # Early-game expansion ramp
    "min_garrison_early": 13,
    "garrison_ramp_turns": 32,
    # Distance exponent ramp
    "distance_power_early": 3.482732599302752,
    "distance_power_late":  0.5051929832754551,
    "distance_ramp_turns":  25,
    # Comets
    "comet_value_multiplier": 0.7187932590356509,
    # Endgame
    "endgame_threshold_turn": 445,
    "endgame_lead_margin": 1.6098319822666625,
    # Lookahead
    # NOTE: step_state/step_state_multi (src/lookahead.py) now launch fleets
    # before production and planet rotation, matching the engine's step order —
    # simulated launch angles previously applied from a post-rotation position
    # the engine never used. This changes the trajectories the lookahead scores.
    # These three params were tuned against the old ordering — do NOT promote
    # until re-tuned. See CLAUDE.md "Pending re-tune: lookahead launch-before-
    # rotation ordering" (rm trials/study.db → run_trials.py → copy winners here
    # → build.py).
    # NOTE (#256): score_state (src/lookahead.py) now also counts in-transit
    # fleet ships (previously only planet-held ships), matching
    # src/endgame.py's total_ships. This changes what my_ships/enemy_ships
    # measure, which changes what these three params were tuned against — do
    # NOT promote until re-tuned via #117 (rm trials/study.db → run_trials.py
    # → copy winners here → build.py).
    "lookahead_turns": 5,
    "lookahead_blend": 0.9032151725931578,
    "lookahead_ship_weight": 0.07240125896738046,
}

SKIP_COMBOS = {
    ("FACTORY",  "HARD_NEUTRAL"),
    ("FACTORY",  "CONTESTED_ENEMY"),
    ("FACTORY",  "HARDENED_ENEMY"),
    ("OUTPOST",  "HARD_NEUTRAL"),
    ("OUTPOST",  "CONTESTED_ENEMY"),
    ("OUTPOST",  "HARDENED_ENEMY"),
}

PARAM_SPACE = {
    "fortress_min_ships":            (20,   60,    int),
    "fortress_min_production":       (2,    5,     int),
    "factory_min_production":        (2,    5,     int),
    "stationary_value_bonus":        (0,    8,     int),
    "weak_ratio":                    (1.1,  2.5,   float),
    "contested_ratio":               (0.8,  1.5,   float),
    "frac_fortress_easy_neutral":    (0.4,  0.9,   float),
    "frac_fortress_hard_neutral":    (0.5,  0.95,  float),
    "frac_fortress_soft_enemy":      (0.4,  0.9,   float),
    "frac_fortress_contested_enemy": (0.5,  0.95,  float),
    "frac_fortress_hardened_enemy":  (0.5,  0.95,  float),
    "frac_factory_easy_neutral":     (0.3,  0.8,   float),
    "frac_factory_soft_enemy":       (0.3,  0.8,   float),
    "frac_outpost_easy_neutral":     (0.2,  0.7,   float),
    "frac_outpost_soft_enemy":       (0.2,  0.7,   float),
    "threat_radius":                 (3.0,  8.0,   float),
    "threat_eta_window":             (10,   50,    int),
    "defense_reinforce_fraction":    (0.3,  0.7,   float),
    "defense_incoming_multiplier":   (0.0,  2.0,   float),
    "eta_buffer":                    (2,    10,    int),
    "min_garrison":                  (5,    30,    int),
    "aggression_max":                (0.7,  1.0,   float),
    "aggression_min":                (0.3,  0.8,   float),
    "min_garrison_early":            (1,    15,    int),
    "garrison_ramp_turns":           (10,   100,   int),
    "distance_power_early":          (2.0,  5.0,   float),
    "distance_power_late":           (0.5,  3.0,   float),
    "distance_ramp_turns":           (10,   150,   int),
    "comet_value_multiplier":        (0.0,  3.0,   float),
    "endgame_threshold_turn":        (380,  490,   int),
    "endgame_lead_margin":           (1.05, 2.0,   float),
    "lookahead_turns":               (1,    5,     int),
    "lookahead_blend":               (0.0,  1.0,   float),
    "lookahead_ship_weight":         (0.001, 0.1,  float),
}

# --- src/lookahead.py ---
"""Lightweight 1–2 turn simulator for lookahead scoring."""



@dataclass
class SimPlanet:
    id: int
    owner: int
    x: float
    y: float
    radius: float
    ships: int
    production: int


@dataclass
class SimFleet:
    owner: int
    x: float
    y: float
    angle: float
    ships: int
    id: int = -1  # sentinel for sim-spawned fleets; real fleets get kaggle id


@dataclass
class GameState:
    planets: list  # list[SimPlanet]
    fleets: list  # list[SimFleet]
    turn: int


def build_state(planets, fleets, turn: int) -> GameState:
    """Convert immutable kaggle namedtuples to mutable SimPlanet/SimFleet objects."""
    sim_planets = [
        SimPlanet(
            id=p.id,
            owner=p.owner,
            x=p.x,
            y=p.y,
            radius=p.radius,
            ships=p.ships,
            production=p.production,
        )
        for p in planets
    ]
    sim_fleets = [
        SimFleet(
            owner=f.owner,
            x=f.x,
            y=f.y,
            angle=f.angle,
            ships=f.ships,
            id=f.id,
        )
        for f in fleets
    ]
    return GameState(planets=sim_planets, fleets=sim_fleets, turn=turn)


def _resolve_combat(planet: SimPlanet, arrivals: list) -> None:
    """Resolve combat on a single planet when one or more fleets arrive.

    Mutates planet.owner and planet.ships in place. Assumes arrivals is non-empty
    (the caller is responsible for skipping planets with no arrivals).

    Four branches:
    1. New owner wins with surviving > 0 ships (minus 1 foothold cost).
    2. Defender holds with surviving > 0 ships.
    3. Exact tie (surviving == 0) won by the incumbent — planet held, 0 ships.
    4. Incumbent loses to combined attackers (surviving < 0) — planet goes neutral.
    """
    # Group by owner; include planet's own garrison as a defender.
    # Neutral planets (owner=-1) defend with their ships under key -1.
    owner_ships: dict[int, int] = {}
    owner_ships[planet.owner] = planet.ships
    for f in arrivals:
        owner_ships[f.owner] = owner_ships.get(f.owner, 0) + f.ships

    # Find the winner (largest total); ties go to current owner.
    winner = max(
        owner_ships, key=lambda o: (owner_ships[o], 1 if o == planet.owner else 0)
    )
    winner_ships = owner_ships[winner]
    total_others = sum(v for o, v in owner_ships.items() if o != winner)
    surviving = winner_ships - total_others

    if surviving > 0 and winner != planet.owner:
        planet.owner = winner
        # -1 ship cost models the "foothold" overhead of taking a new planet.
        # The real engine doesn't have this cost; it's a deliberate pessimism
        # bias in the 1-turn lookahead to avoid over-valuing conquest moves.
        planet.ships = surviving - 1
    elif surviving > 0:
        planet.ships = surviving
    elif surviving == 0 and winner == planet.owner:
        # EXACT tie won by the incumbent owner (ties break to current owner).
        # The defender holds the planet with no ships to spare, rather than
        # collapsing to neutral — keeps the lookahead from undervaluing holds.
        # For a neutral planet (owner=-1) this preserves neutral-stays-neutral.
        # Guarded on ``surviving == 0``: when the incumbent is only the
        # largest SINGLE stack but loses to the COMBINED attackers
        # (surviving < 0), it must NOT retain the planet — that falls through
        # to the neutral branch below.
        planet.ships = 0
    else:
        # No surviving victor — an exact tie not won by the incumbent, or the
        # incumbent was the largest single stack but lost to the combined
        # attackers (surviving < 0). The planet goes neutral with 0 ships.
        planet.owner = -1
        planet.ships = 0


def step_state(
    state: GameState,
    move,
    player: int,
    angular_velocity: float,
    opponent_fn=None,
) -> GameState:
    """Simulate ONE turn forward.

    Args:
        state: Current game state (will be mutated in place; caller should not
               reuse it after calling step_state).
        move: [planet_id, angle, ships] or None.
        player: The acting player's index.
        angular_velocity: Global orbital angular velocity (rad/turn).
        opponent_fn: Optional callable (state) -> list[list]. If provided,
                     opponent moves are applied after our fleet launch and before
                     fleet movement.

    Returns:
        The mutated GameState after one simulated turn.
    """
    moves = [] if move is None else [move]
    return step_state_multi(state, moves, player, angular_velocity, opponent_fn)


def step_state_multi(
    state: GameState,
    moves,
    player: int,
    angular_velocity: float,
    opponent_fn=None,
) -> GameState:
    """Simulate ONE turn forward with a list of own-player moves.

    Identical to step_state except the launch phase iterates *moves* (a list of
    [planet_id, angle, ships]) rather than a single optional move.  An empty
    list applies no own launches.  Steps 1b, 2, 3, 4, and 5 are byte-for-byte
    equivalent to step_state.

    Args:
        state: Current game state (mutated in place; caller should not reuse).
        moves: List of [planet_id, angle, ships] launch instructions. An empty
               list produces no own launches. Moves whose source has insufficient
               ships are silently skipped.
        player: The acting player's index.
        angular_velocity: Global orbital angular velocity (rad/turn).
        opponent_fn: Optional callable (state) -> list[list]. Invoked exactly
                     once; opponent moves are applied after own launches.

    Returns:
        The mutated GameState after one simulated turn.
    """
    # --- Step 1: Launch one fleet per move (skips moves with insufficient ships) ---
    # Matches the engine's step order (orbit_wars.py interpreter): Fleet Launch
    # happens before Production and Planet Movement & Sweep, so the launch angle
    # is applied from each source planet's PRE-rotation position — exactly the
    # coordinates plan_expansion used to compute the angle in the first place.
    for move in moves:
        planet_id, angle, ships_to_send = move[0], move[1], move[2]
        source = next((p for p in state.planets if p.id == planet_id), None)
        if source is not None and source.ships >= ships_to_send:
            source.ships -= ships_to_send
            state.fleets.append(
                SimFleet(
                    owner=player,
                    x=source.x + math.cos(angle) * (source.radius + 0.1),
                    y=source.y + math.sin(angle) * (source.radius + 0.1),
                    angle=angle,
                    ships=ships_to_send,
                )
            )

    # --- Step 1b: Opponent fleet launches ---
    if opponent_fn is not None:
        opp_moves = opponent_fn(state)
        for opp_move in opp_moves:
            planet_id, angle, ships = opp_move[0], opp_move[1], opp_move[2]
            opp_source = next((p for p in state.planets if p.id == planet_id), None)
            if opp_source is not None and opp_source.ships >= ships:
                opp_source.ships -= ships
                state.fleets.append(
                    SimFleet(
                        owner=1 - player,
                        x=opp_source.x + math.cos(angle) * (opp_source.radius + 0.1),
                        y=opp_source.y + math.sin(angle) * (opp_source.radius + 0.1),
                        angle=angle,
                        ships=ships,
                    )
                )

    # --- Step 2: Production ---
    for planet in state.planets:
        if planet.owner != -1:
            planet.ships += planet.production

    # --- Step 3: Rotate orbiting planets ---
    for sim_planet in state.planets:
        new_x, new_y = predict_planet_position(sim_planet, angular_velocity, 1)
        sim_planet.x = new_x
        sim_planet.y = new_y

    # --- Step 4: Move all fleets ---
    for fleet in state.fleets:
        speed = fleet_speed(fleet.ships)
        fleet.x += speed * math.cos(fleet.angle)
        fleet.y += speed * math.sin(fleet.angle)

    # --- Step 5: Combat ---
    # Single pass: assign each fleet to the first planet it lands on, or keep flying.
    remaining_fleets = []
    planet_arrivals: dict[int, list] = {p.id: [] for p in state.planets}
    for fleet in state.fleets:
        landed = False
        for planet in state.planets:
            dist = distance(fleet.x, fleet.y, planet.x, planet.y)
            if dist <= planet.radius:
                planet_arrivals[planet.id].append(fleet)
                landed = True
                break
        if not landed:
            remaining_fleets.append(fleet)

    for planet in state.planets:
        arrivals = planet_arrivals[planet.id]
        if not arrivals:
            continue
        _resolve_combat(planet, arrivals)

    # Keep only fleets that didn't land on any planet
    state.fleets = remaining_fleets

    state.turn += 1
    return state


def score_state(state: GameState, player: int, ship_weight: float = 0.01) -> float:
    """Score a GameState from `player`'s perspective."""
    my_prod = sum_owned(state.planets, player, attr="production")
    enemy_prod = sum_owned(state.planets, player, attr="production", enemy=True)
    # Includes in-transit fleet ships (not just planet-held ships), matching
    # src/endgame.py's total_ships — a fleet launched by step_state and still
    # flying at the lookahead horizon no longer vanishes from the score. This
    # changes the measurement lookahead_blend/lookahead_ship_weight/lookahead_turns
    # (src/config.py) were tuned against; not for promotion until re-tuned via #117.
    my_ships = sum_owned(state.planets, player) + sum_owned(state.fleets, player)
    enemy_ships = sum_owned(state.planets, player, enemy=True) + sum_owned(
        state.fleets, player, enemy=True
    )
    return (my_prod - enemy_prod) + ship_weight * (my_ships - enemy_ships)


def score_candidate_lookahead(
    initial_planets,
    fleets,
    turn: int,
    candidate_move,
    player: int,
    angular_velocity: float,
    opponent_fn,
    params,
    plan_moves_fn,
) -> float:
    """Score a candidate move by simulating it forward and scoring the result.

    Builds a state from the current board, applies our `candidate_move` plus the
    opponent's response (T+1), then rolls forward `lookahead_turns - 1` more turns
    with both sides applying their full planned move lists, and returns `score_state`
    from `player`'s view. `plan_moves_fn` is INJECTED rather than imported so this
    module never depends on strategy.py — the greedy roll-forward calls back into the
    real planner without creating a circular import. Behaviour-preserving extraction
    of the block formerly inline in strategy.plan_expansion.
    """
    # T+1: apply our candidate move + opponent response.
    state = build_state(initial_planets, fleets, turn)
    state = step_state(state, candidate_move, player, angular_velocity, opponent_fn)
    # T+2..N: both players apply their full planned move lists (lookahead disabled).
    n_extra = params.get("lookahead_turns", 1) - 1
    # Loop-invariant: greedy_params depends only on params, never on the evolving
    # state — build it once, mirroring the hoist in commit e9750e6 (#49).
    greedy_params = {**params, "lookahead_blend": 0.0}
    for _ in range(n_extra):
        our_greedy = plan_moves_fn(
            state.planets,
            state.fleets,
            player,
            angular_velocity,
            turn=state.turn,
            params=greedy_params,
            initial_planets=initial_planets,
        )
        # Fresh opponent response from the evolved state (not the frozen initial state).
        opp_greedy = plan_moves_fn(
            state.planets,
            state.fleets,
            1 - player,
            angular_velocity,
            turn=state.turn,
            params=greedy_params,
            initial_planets=initial_planets,
        )
        fresh_opp_fn = lambda s, m=opp_greedy: m  # noqa: E731
        state = step_state_multi(state, our_greedy, player, angular_velocity, fresh_opp_fn)
    return score_state(state, player, params.get("lookahead_ship_weight", 0.01))

# --- src/comets.py ---
"""Comet utilities for Orbit Wars.

Comets are planets that temporarily visit the map. Their production value should
be scaled by a multiplier so the agent can treat them as less (or more) attractive
targets than permanent planets.
"""


def get_comet_ids(obs: dict) -> set[int]:
    """Return the set of planet IDs that are currently comets.

    Uses ``obs.get("comet_planet_ids") or []`` so the result is always a set
    even when the key is absent or the value is None.
    """
    return set(obs.get("comet_planet_ids") or [])


def effective_production(planet: Planet, comet_ids: set, multiplier: float) -> float:
    """Return the production value used for scoring this planet.

    If *planet* is in *comet_ids* the raw production is scaled by *multiplier*;
    otherwise the raw production is returned unchanged.

    A *multiplier* of 0.0 makes comets invisible to targeting.
    A *multiplier* of 2.0 doubles their apparent value.
    Non-comet planets always return their raw production regardless of *multiplier*.
    """
    if planet.id in comet_ids:
        return planet.production * multiplier
    return float(planet.production)

# --- src/endgame.py ---
def total_ships(planets: list, fleets: list, player: int) -> int:
    """Count combined ships for player across all planets and in-transit fleets."""
    return sum_owned(planets, player) + sum_owned(fleets, player)


def should_play_defensive(
    planets: list,
    fleets: list,
    player: int,
    turn: int,
    threshold_turn: int,
    lead_margin: float,
) -> bool:
    """Return True when winning by lead_margin and past threshold_turn.

    Returns False when enemy_ships == 0 to avoid ZeroDivisionError.
    Returns False when losing (ratio < lead_margin), even past threshold turn.
    Returns False before threshold turn, even when winning.
    """
    if turn < threshold_turn:
        return False

    # Enemy bucket spans every non-player, non-neutral owner over both planets and
    # in-transit fleets — the same planets+fleets shape as total_ships above.
    # sum_owned(..., enemy=True) is the shared definition of that filter, which
    # score_state in lookahead.py uses too.
    enemy_ships = sum_owned(planets, player, enemy=True) + sum_owned(
        fleets, player, enemy=True
    )

    if enemy_ships == 0:
        return False

    my_ships = total_ships(planets, fleets, player)
    return (my_ships / enemy_ships) >= lead_margin

# --- src/strategy.py ---
Threat = namedtuple("Threat", ["planet_id", "incoming_ships", "eta"])

# Safety cap for ETA fixed-point loops: the orbit/intercept system may not analytically
# converge, so we bound the iteration count rather than looping forever.
ETA_CONVERGENCE_ITERS = 10


def _turn_ramp(turn: int, ramp_turns: int, start: float, end: float) -> float:
    """Linearly interpolate from start to end over [0, ramp_turns], clamped at ramp_turns."""
    if ramp_turns <= 0:
        return end
    t = min(turn, ramp_turns) / ramp_turns
    return start + t * (end - start)


def aggression(turn: int, params: dict = PARAMS) -> float:
    return _turn_ramp(
        turn, params["game_length"], params["aggression_max"], params["aggression_min"]
    )


def classify_own(planet: Planet, threatened_ids: set, params: dict = PARAMS) -> str:
    if planet.id in threatened_ids:
        return "THREATENED"
    if (
        planet.ships >= params["fortress_min_ships"]
        and planet.production >= params["fortress_min_production"]
    ):
        return "FORTRESS"
    if planet.production >= params["factory_min_production"]:
        return "FACTORY"
    return "OUTPOST"


def classify_neutral(target: Planet, ships_to_send: int, params: dict = PARAMS) -> str:
    if target.ships == 0:
        return "EASY_NEUTRAL"
    ratio = ships_to_send / target.ships
    if ratio > params["weak_ratio"]:
        return "EASY_NEUTRAL"
    return "HARD_NEUTRAL"


def classify_enemy(
    target: Planet, ships_to_send: int, eta: int, params: dict = PARAMS
) -> str:
    expected_defenders = target.ships + target.production * eta
    if expected_defenders == 0:
        return "SOFT_ENEMY"
    ratio = ships_to_send / expected_defenders
    if ratio > params["weak_ratio"]:
        return "SOFT_ENEMY"
    if ratio > params["contested_ratio"]:
        return "CONTESTED_ENEMY"
    return "HARDENED_ENEMY"


def detect_threats(
    my_planets: list[Planet],
    fleets: list[Fleet],
    player: int,
    angular_velocity: float,
    params: dict = PARAMS,
) -> list:
    # Aggregate every inbound fleet per planet: planet_id -> [summed_ships, earliest_eta].
    # Multiple enemy fleets converging on one planet collapse into a SINGLE threat so
    # handle_threats sizes reinforcement against the combined attack, not just one fleet.
    # Use id(fleet) (object identity) rather than fleet.id so that distinct fleet
    # objects sharing the same .id value (e.g. sim-spawned sentinels where id=-1)
    # each contribute their ships exactly once.
    seen: set[tuple[int, int]] = set()
    # planet_id -> (summed_ships, earliest_eta). An explicit 2-tuple keeps each
    # slot self-documenting (no positional [0]/[1] mutation to accidentally swap).
    inbound_by_planet: dict[int, tuple[int, int]] = {}
    # (planet.id, t) -> (px, py). predict_planet_position depends only on
    # (planet, t), not on the enemy fleet, so precompute it once per planet/t
    # here rather than recomputing it for every enemy fleet in the loop below.
    # Skip the precompute entirely when no enemy fleets are present — the loop
    # below never consults planet_positions in that case.
    planet_positions: dict[tuple[int, int], tuple[float, float]] = {}
    if any(fleet.owner != player for fleet in fleets):
        planet_positions = {
            (planet.id, t): predict_planet_position(planet, angular_velocity, t - 1)
            for t in range(1, params["threat_eta_window"] + 1)
            for planet in my_planets
        }
    for fleet in fleets:
        if fleet.owner == player:
            continue
        speed = fleet_speed(fleet.ships)
        cos_a = math.cos(fleet.angle)
        sin_a = math.sin(fleet.angle)
        for t in range(1, params["threat_eta_window"] + 1):
            # Check the fleet's straight-line segment for interval [t-1, t] against
            # each planet's position at the start of that interval.  This catches
            # fleets whose closest approach falls between two integer samples.
            fx0 = fleet.x + (t - 1) * speed * cos_a
            fy0 = fleet.y + (t - 1) * speed * sin_a
            fx1 = fleet.x + t * speed * cos_a
            fy1 = fleet.y + t * speed * sin_a
            for planet in my_planets:
                # seen guards a single fleet object from contributing its ships
                # more than once to the same planet (it may stay in-radius across
                # several t). Keyed on object identity so fleets sharing .id=-1
                # (lookahead sim-spawned sentinels) are not collapsed.
                if (id(fleet), planet.id) in seen:
                    continue
                px, py = planet_positions[(planet.id, t)]
                if _min_dist_pt_to_segment(px, py, fx0, fy0, fx1, fy1) < params["threat_radius"]:
                    seen.add((id(fleet), planet.id))
                    if planet.id in inbound_by_planet:
                        prev_ships, prev_eta = inbound_by_planet[planet.id]
                        # sum ships across fleets; keep the earliest sighting as ETA
                        inbound_by_planet[planet.id] = (
                            prev_ships + fleet.ships,
                            min(prev_eta, t),
                        )
                    else:
                        inbound_by_planet[planet.id] = (fleet.ships, t)
    return [
        Threat(planet_id=pid, incoming_ships=ships, eta=eta)
        for pid, (ships, eta) in inbound_by_planet.items()
    ]


def handle_threats(
    threats: list,
    owned: list[Planet],
    own_classes: dict,
    angular_velocity: float,
    params: dict = PARAMS,
) -> list[list]:
    moves = []
    already_used: set[int] = set()
    for threat in threats:
        target = next((p for p in owned if p.id == threat.planet_id), None)
        if target is None:
            continue
        for source in owned:
            if source.id == threat.planet_id or source.id in already_used:
                continue
            if own_classes.get(source.id) not in ("FORTRESS", "FACTORY"):
                # classify_own returns "THREATENED" (not "FORTRESS") when a fleet is inbound,
                # so THREATENED planets are naturally excluded here
                continue
            # Flat fraction (legacy behavior) vs. magnitude-aware reinforcement that
            # scales with the size of the incoming attack. At multiplier == 0.0,
            # magnitude collapses to 0 and ships_to_send == flat — byte-for-byte
            # identical to the pre-feature behavior.
            flat = int(source.ships * params["defense_reinforce_fraction"])
            magnitude = int(
                threat.incoming_ships * params["defense_incoming_multiplier"]
            )
            # Cap magnitude-driven growth so the source keeps min_garrison, but never
            # below the flat baseline (preserves the legacy floor when the knob is 0).
            # max(flat, min(max(flat, magnitude), cap)) collapses to max(flat, min(magnitude, cap)):
            # when magnitude >= flat both forms agree; when magnitude < flat both reduce to flat.
            cap = source.ships - params["min_garrison"]
            ships_to_send = max(flat, min(magnitude, cap))
            if ships_to_send < params["min_garrison"]:
                continue
            future_x, future_y, eta = intercept(
                source, target, angular_velocity, ships_to_send
            )
            if eta <= threat.eta - params["eta_buffer"]:
                if path_crosses_sun(source.x, source.y, future_x, future_y):
                    continue
                angle = angle_to_target(source.x, source.y, future_x, future_y)
                moves.append([source.id, angle, ships_to_send])
                already_used.add(source.id)
                break
    return moves


def _effective_min_garrison(turn: int, params: dict) -> int:
    """Linearly ramp min_garrison from min_garrison_early up to min_garrison."""
    early = params["min_garrison_early"]
    full = params["min_garrison"]
    ramp = params["garrison_ramp_turns"]
    return int(_turn_ramp(turn, ramp, early, full))


def _effective_distance_power(turn: int, params: dict) -> float:
    """Linearly ramp distance exponent from distance_power_early down to distance_power_late."""
    return _turn_ramp(
        turn,
        params["distance_ramp_turns"],
        params["distance_power_early"],
        params["distance_power_late"],
    )


def _blended_best(candidates: list, blend: float):
    """Select the winning (target, fraction, future_x, future_y) from scored expansion candidates.

    ``candidates`` is a list of ``(greedy_score, lookahead_score, target, fraction, future_x, future_y)``.
    A single candidate or ``blend == 0.0`` takes the greedy fast-path (highest
    greedy score wins). Otherwise greedy and lookahead scores are each min-max
    normalized to ``[0, 1]`` — the ``+1e-9`` guards against a zero range when all
    candidates share a score — and combined as ``(1 - blend) * ng + blend * nl``.
    Returns ``(target, fraction, future_x, future_y)`` so the caller can reuse
    the already-computed intercept geometry without a redundant ``intercept()`` call.
    """
    if len(candidates) == 1 or blend == 0.0:
        best = max(candidates, key=lambda c: c[0])
        return best[2], best[3], best[4], best[5]

    lo_g = min(c[0] for c in candidates)
    hi_g = max(c[0] for c in candidates)
    lo_l = min(c[1] for c in candidates)
    hi_l = max(c[1] for c in candidates)
    scored = []
    for greedy, look, tgt, frac, fx, fy in candidates:
        ng = (greedy - lo_g) / (hi_g - lo_g + 1e-9)
        nl = (look - lo_l) / (hi_l - lo_l + 1e-9)
        final = (1 - blend) * ng + blend * nl
        scored.append((final, tgt, frac, fx, fy))
    best_scored = max(scored, key=lambda x: x[0])
    return best_scored[1], best_scored[2], best_scored[3], best_scored[4]


def _build_opponent_fn(initial_planets, fleets, turn, player, angular_velocity, params, blend):
    """Return a frozen opponent_fn (state -> precomputed moves) for lookahead, or None
    when blend==0 or inputs are missing. Forces blend=0 in the opponent plan to terminate recursion.

    Precompute the opponent's frozen response ONCE per plan_expansion call. Every
    input (initial_planets, fleets, turn, player, angular_velocity, params) is
    loop-invariant, so the result is identical for every source planet — hoisted
    out of the `for source in owned:` loop in plan_expansion to avoid recomputing a
    full opponent plan_moves per owned planet every turn (the lookahead path runs
    with lookahead_blend≈0.97 in real games and across self-play). Forces blend=0 to
    prevent recursive lookahead (recursion termination).
    """
    use_lookahead = blend > 0 and initial_planets is not None and fleets is not None
    if not use_lookahead:
        return None

    opp_player = 1 - player
    greedy_params_opp = {**params, "lookahead_blend": 0.0}
    opp_base = build_state(initial_planets, fleets, turn)
    opp_moves = plan_moves(
        opp_base.planets,
        opp_base.fleets,
        opp_player,
        angular_velocity,
        turn=turn,
        params=greedy_params_opp,
        initial_planets=initial_planets,
    )
    return lambda state, m=opp_moves: m  # noqa: E731


def _generate_candidates(
    source: Planet,
    src_class: str,
    targets: list[Planet],
    dist_power: float,
    agg: float,
    blend: float,
    angular_velocity: float,
    params: dict,
    comet_ids: set,
    comet_velocities: dict | None,
    opponent_fn,
    initial_planets,
    fleets,
    player: int,
    turn: int,
) -> list:
    """Return scored expansion candidates for one source planet.

    Each candidate is a ``(greedy_score, lookahead_score, target, fraction,
    future_x, future_y)`` tuple, scored via classification, intercept,
    ``can_capture``, sun-path checks, greedy scoring, and optional lookahead
    scoring against ``opponent_fn``.
    """
    use_lookahead = blend > 0 and initial_planets is not None and fleets is not None
    # Use full fleet for classification so FACTORY correctly sees adjacent
    # enemies as SOFT rather than CONTESTED (half-fleet underestimates ratio).
    probe_ships = source.ships

    candidates = []  # list of (greedy_score, lookahead_score, target, fraction, future_x, future_y)

    for target in targets:
        if target.owner == -1:
            tgt_class = classify_neutral(target, probe_ships, params)
        else:
            probe_result = intercept(
                source,
                target,
                angular_velocity,
                probe_ships,
                comet_ids,
                comet_velocities,
            )
            if probe_result[0] is None:
                continue
            _, _, probe_eta = probe_result
            tgt_class = classify_enemy(target, probe_ships, probe_eta, params)

        if (src_class, tgt_class) in SKIP_COMBOS:
            continue
        # Deliberately optional: SKIP_COMBOS (src/config.py) means some
        # (src_class, tgt_class) pairs have no frac_* key in PARAMS at all,
        # so .get() + the None-check below is the documented control flow.
        fraction = params.get(f"frac_{src_class.lower()}_{tgt_class.lower()}")
        if fraction is None:
            continue

        ships_to_send = max(1, int(source.ships * fraction * agg))
        intercept_result = intercept(
            source,
            target,
            angular_velocity,
            ships_to_send,
            comet_ids,
            comet_velocities,
        )
        if intercept_result[0] is None:
            continue
        future_x, future_y, eta = intercept_result
        if not can_capture(ships_to_send, target, eta):
            continue
        if path_crosses_sun(source.x, source.y, future_x, future_y):
            continue

        bonus = params["stationary_value_bonus"] if is_stationary(target) else 0
        eff_prod = effective_production(
            target, comet_ids, params["comet_value_multiplier"]
        )
        greedy_score = (eff_prod + bonus) / (eta + 1) ** dist_power

        # Lookahead score — simulate the candidate forward and score it.
        # opponent_fn is constructed once per plan_expansion call and passed
        # in, reused across every source planet and candidate target.
        if use_lookahead:
            candidate_move = [
                source.id,
                angle_to_target(source.x, source.y, future_x, future_y),
                ships_to_send,
            ]
            # plan_moves injected so lookahead.py stays free of a strategy import.
            lookahead_score = score_candidate_lookahead(
                initial_planets,
                fleets,
                turn,
                candidate_move,
                player,
                angular_velocity,
                opponent_fn,
                params,
                plan_moves,
            )
        else:
            lookahead_score = greedy_score  # fallback keeps blend=0 equivalent

        candidates.append((greedy_score, lookahead_score, target, fraction, future_x, future_y))

    return candidates


def _try_send(
    source: Planet,
    target: Planet,
    ships: int,
    angular_velocity: float,
    comet_ids: set = frozenset(),
    comet_velocities: dict | None = None,
    *,
    validate: bool = False,
    aim: tuple[float, float] | None = None,
) -> list | None:
    """Build a ``[source.id, angle, ships]`` move, or ``None`` if un-sendable.

    Runs ``intercept`` to find the aim point and returns ``None`` when it can't
    find one. When ``validate=True``, also rejects when ``can_capture`` fails or
    the path crosses the sun.

    ``aim`` supplies an ``(future_x, future_y)`` already computed by the caller,
    skipping the intercept entirely — the primary launch reuses the winning
    candidate's geometry from the scoring loop rather than recomputing it.
    Incompatible with ``validate=True``, which needs the ``eta`` only
    ``intercept`` returns; that combination is a programming error.
    """
    if aim is not None:
        if validate:
            raise ValueError("aim= cannot be combined with validate=True (needs eta)")
        future_x, future_y = aim
    else:
        future_x, future_y, eta = intercept(
            source, target, angular_velocity, ships, comet_ids, comet_velocities
        )
        if future_x is None:
            return None
        if validate:
            if not can_capture(ships, target, eta):
                return None
            if path_crosses_sun(source.x, source.y, future_x, future_y):
                return None
    return [source.id, angle_to_target(source.x, source.y, future_x, future_y), ships]


def plan_expansion(
    owned: list[Planet],
    neutrals: list[Planet],
    enemies: list[Planet],
    own_classes: dict,
    angular_velocity: float,
    agg: float = 1.0,
    params: dict = PARAMS,
    comet_ids: set = frozenset(),
    initial_planets=None,
    fleets=None,
    player: int = 0,
    turn: int = 0,
    comet_velocities: dict | None = None,
) -> list[list]:
    moves = []
    targets = neutrals + enemies
    min_garrison = int(_effective_min_garrison(turn, params) / agg)
    dist_power = _effective_distance_power(turn, params)
    blend = params["lookahead_blend"]
    opponent_fn = _build_opponent_fn(
        initial_planets, fleets, turn, player, angular_velocity, params, blend
    )

    for source in owned:
        src_class = own_classes.get(source.id, "OUTPOST")
        if src_class == "THREATENED":
            continue
        if source.ships < min_garrison:
            continue

        candidates = _generate_candidates(
            source,
            src_class,
            targets,
            dist_power,
            agg,
            blend,
            angular_velocity,
            params,
            comet_ids,
            comet_velocities,
            opponent_fn,
            initial_planets,
            fleets,
            player,
            turn,
        )

        if not candidates:
            continue

        best_target, best_fraction, best_fx, best_fy = _blended_best(candidates, blend)

        # Primary fleet — the candidate was fully validated during scoring, and
        # first_send equals the ships_to_send that produced (best_fx, best_fy),
        # so the geometry is reused via aim= and no intercept is repeated here.
        ships_remaining = source.ships
        first_send = max(1, int(ships_remaining * best_fraction * agg))
        move = _try_send(
            source,
            best_target,
            first_send,
            angular_velocity,
            comet_ids,
            comet_velocities,
            aim=(best_fx, best_fy),
        )
        if move is None:
            continue
        moves.append(move)
        ships_remaining -= first_send

        # Multi-target: drain excess ships to lower-scored candidates
        if ships_remaining > min_garrison:
            already_sent = {best_target.id}
            # Drain ranks by raw greedy c[0], not blended: lookahead is expensive and leftover-fleet stakes are low.
            for _, _, extra_target, extra_fraction, _, _ in sorted(
                candidates, key=lambda c: c[0], reverse=True
            ):
                if ships_remaining <= min_garrison:
                    break
                if extra_target.id in already_sent:
                    continue
                extra_send = max(1, int(ships_remaining * extra_fraction * agg))
                # Don't drop below min_garrison. The loop guard above ensures
                # ships_remaining > min_garrison here, so the clamped value is >= 1.
                if ships_remaining - extra_send < min_garrison:
                    extra_send = ships_remaining - min_garrison
                extra_move = _try_send(
                    source,
                    extra_target,
                    extra_send,
                    angular_velocity,
                    comet_ids,
                    comet_velocities,
                    validate=True,
                )
                if extra_move is None:
                    continue
                moves.append(extra_move)
                ships_remaining -= extra_send
                already_sent.add(extra_target.id)

    return moves


def plan_moves(
    planets: list[Planet],
    fleets: list[Fleet],
    player: int,
    angular_velocity: float,
    turn: int = 0,
    params: dict = PARAMS,
    comet_ids: set = frozenset(),
    initial_planets=None,
    comet_velocities: dict | None = None,
) -> list[list]:
    owned = my_planets(planets, player)
    neutrals = neutral_planets(planets)
    enemies = enemy_planets(planets, player)

    if not owned:
        return []

    agg = aggression(turn, params)
    threats = detect_threats(owned, fleets, player, angular_velocity, params)
    threatened_ids = {t.planet_id for t in threats}
    own_classes = {p.id: classify_own(p, threatened_ids, params) for p in owned}

    defense_moves = handle_threats(
        threats, owned, own_classes, angular_velocity, params
    )

    if should_play_defensive(
        planets,
        fleets,
        player,
        turn,
        params["endgame_threshold_turn"],
        params["endgame_lead_margin"],
    ):
        return defense_moves

    defense_used = {m[0] for m in defense_moves}

    expansion_owned = [p for p in owned if p.id not in defense_used]
    expansion_classes = {k: v for k, v in own_classes.items() if k not in defense_used}
    expansion_moves = plan_expansion(
        expansion_owned,
        neutrals,
        enemies,
        expansion_classes,
        angular_velocity,
        agg,
        params,
        comet_ids,
        initial_planets=initial_planets,
        fleets=fleets,
        player=player,
        turn=turn,
        comet_velocities=comet_velocities,
    )

    return defense_moves + expansion_moves


def my_planets(planets: list[Planet], player: int) -> list[Planet]:
    return [p for p in planets if p.owner == player]


def neutral_planets(planets: list[Planet]) -> list[Planet]:
    return [p for p in planets if p.owner == -1]


def enemy_planets(planets: list[Planet], player: int) -> list[Planet]:
    return [p for p in planets if p.owner not in (-1, player)]


def _intercept_comet_linear(
    sx: float,
    sy: float,
    tx: float,
    ty: float,
    vx: float,
    vy: float,
    ships: int,
) -> tuple[float, float, int] | None:
    """Iterative linear intercept for a comet moving at constant velocity.

    Returns (fx, fy, eta) when a safe on-board intercept converges, or None
    when the predicted aim point or the fleet's actual endpoint (accounting
    for overshoot) would leave the board.
    """
    speed = fleet_speed(ships)
    eta = turns_to_arrive(sx, sy, tx, ty, ships)
    fx, fy = tx, ty
    for _ in range(ETA_CONVERGENCE_ITERS):
        fx = tx + vx * eta
        fy = ty + vy * eta
        if not (BOARD_MIN <= fx <= BOARD_MAX and BOARD_MIN <= fy <= BOARD_MAX):
            return None  # comet off-board at predicted intercept time
        new_eta = turns_to_arrive(sx, sy, fx, fy, ships)
        if new_eta == eta:
            break
        eta = new_eta

    # Check fleet endpoint for overshoot: fleet travels eta*speed units in a
    # straight line; if that overshoots past the aim point toward the board
    # edge the fleet exits the board.
    d = distance(fx, fy, sx, sy)
    if d > 1e-9:
        scale = (eta * speed) / d
        ex = sx + scale * (fx - sx)
        ey = sy + scale * (fy - sy)
        if not (BOARD_MIN <= ex <= BOARD_MAX and BOARD_MIN <= ey <= BOARD_MAX):
            return None

    return fx, fy, eta


def intercept(
    source: Planet,
    target: Planet,
    angular_velocity: float,
    ships_to_send: int,
    comet_ids: set = frozenset(),
    comet_velocities: dict | None = None,
) -> tuple[float, float, int] | tuple[None, None, None]:
    """Return (future_x, future_y, eta) predicting the target's future position.

    Returns (None, None, None) for comet targets that cannot be safely
    intercepted — caller must skip those targets.

    For comets uses linear velocity extrapolation; for regular orbiting planets
    iterates until ETA converges.
    """
    if target.id in comet_ids:
        vel = (comet_velocities or {}).get(target.id)
        if not vel:
            # No velocity data yet (first sighting) — cannot aim accurately
            return None, None, None
        result = _intercept_comet_linear(
            source.x, source.y, target.x, target.y, vel[0], vel[1], ships_to_send
        )
        if result is None:
            return None, None, None
        return result

    # Regular orbiting planet: iterate until ETA converges
    eta = turns_to_arrive(source.x, source.y, target.x, target.y, ships_to_send)
    future_x, future_y = target.x, target.y
    for _ in range(ETA_CONVERGENCE_ITERS):
        future_x, future_y = predict_planet_position(target, angular_velocity, eta)
        new_eta = turns_to_arrive(source.x, source.y, future_x, future_y, ships_to_send)
        if new_eta == eta:
            break
        eta = new_eta
    return future_x, future_y, eta


def can_capture(ships_to_send: int, target: Planet, eta: int) -> bool:
    """True if our fleet will outnumber the target on arrival.
    Neutral planets don't produce ships (only owned planets do per game engine),
    so only add production*eta for enemy planets."""
    if target.owner == -1:
        expected_defenders = target.ships
    else:
        expected_defenders = target.ships + target.production * eta
    return ships_to_send > expected_defenders

# --- src/agent.py ---
_initial_planets = None
_prev_comet_positions: dict[int, tuple[float, float]] = {}


def plan_turn(obs, initial_planets, prev_comet_positions, params=None):
    """Shared per-turn wrapper: parse obs, track comet velocities, plan moves.

    Both the deployed agent (``agent`` below) and the self-play tuning agent
    (``trials.game_runner.make_agent``) call this so tuning and deployment
    exercise the *same* comet-aware targeting code. A comet's velocity is
    estimated from its one-turn position delta between sightings and handed to
    ``plan_moves`` as ``comet_velocities`` so the linear-intercept path is
    actually attempted.

    State is threaded explicitly rather than stored here, so each caller keeps
    its own: the deployed agent uses module globals while each trial closure
    uses its own locals (parallel games mustn't share state). Returns
    ``(moves, new_initial_planets, new_prev_comet_positions)``.
    """
    planets = [Planet(*p) for p in obs.get("planets", [])]
    fleets = [Fleet(*f) for f in obs.get("fleets", [])]
    player = obs.get("player", 0)
    angular_velocity = obs.get("angular_velocity", 0.0)
    turn = obs.get("step", 0)
    comet_ids = get_comet_ids(obs)

    if turn == 0 or initial_planets is None:
        initial_planets = planets
        prev_comet_positions = {}

    # Build comet velocity estimates from position deltas (one turn apart)
    comet_velocities: dict[int, tuple[float, float]] = {}
    current_comet_positions: dict[int, tuple[float, float]] = {}
    for p in planets:
        if p.id in comet_ids:
            current_comet_positions[p.id] = (p.x, p.y)
            if p.id in prev_comet_positions:
                px, py = prev_comet_positions[p.id]
                comet_velocities[p.id] = (p.x - px, p.y - py)

    kwargs = dict(
        comet_ids=comet_ids,
        comet_velocities=comet_velocities,
        initial_planets=initial_planets,
    )
    if params is not None:
        kwargs["params"] = params

    moves = plan_moves(planets, fleets, player, angular_velocity, turn, **kwargs)
    return moves, initial_planets, current_comet_positions


def agent(obs: dict) -> list[list]:
    global _initial_planets, _prev_comet_positions
    moves, _initial_planets, _prev_comet_positions = plan_turn(
        obs, _initial_planets, _prev_comet_positions,
    )
    return moves

