"""Hand-authored prose in docs/wiki must quote PARAMS defaults matching src/config.py.

Home.md, Game-Loop.md, and Decision-Trace.md each hard-code the
`fortress_min_ships`, `factory_min_production`, `threat_eta_window`,
`threat_radius`, and `defense_reinforce_fraction` defaults in prose. Unlike
`docs/wiki/src/config.md` (auto-generated by `generate_config.py` from PARAMS/
PARAM_SPACE and always current), these three pages drifted independently and
even disagreed with each other (issue #215). This test pins the quoted figures
to the live `src/config.py` PARAMS values so they cannot silently rot again.
"""
from pathlib import Path

from src.config import PARAMS

REPO_ROOT = Path(__file__).parent.parent
WIKI = REPO_ROOT / "docs" / "wiki"

FORTRESS_MIN_SHIPS = PARAMS["fortress_min_ships"]
FORTRESS_MIN_PRODUCTION = PARAMS["fortress_min_production"]
FACTORY_MIN_PRODUCTION = PARAMS["factory_min_production"]
THREAT_ETA_WINDOW = PARAMS["threat_eta_window"]
THREAT_RADIUS = PARAMS["threat_radius"]
DEFENSE_REINFORCE_FRACTION = PARAMS["defense_reinforce_fraction"]

THREAT_RADIUS_2DP = f"{THREAT_RADIUS:.2f}"
DEFENSE_REINFORCE_PCT = f"{DEFENSE_REINFORCE_FRACTION * 100:.2f}%"


class TestHomeDoc:
    """Home.md's other #215 figures (the PARAMS key count and the Module
    Inventory line-count column) no longer exist: issue #319 deleted the
    `Lines` column and replaced the transcribed key count with a cite-by-name
    reference, and `tests/test_docs_module_inventory.py` now forbids either
    from returning. Only the prose thresholds below remain to pin.
    """

    def test_default_thresholds_line_matches_params(self):
        text = (WIKI / "Home.md").read_text()
        expected = (
            f"Default thresholds: {FORTRESS_MIN_SHIPS} ships / "
            f"{FORTRESS_MIN_PRODUCTION} prod (fortress), "
            f"{FACTORY_MIN_PRODUCTION} prod (factory)"
        )
        assert expected in text


class TestGameLoopDoc:
    def test_threat_detection_defaults_match_params(self):
        text = (WIKI / "Game-Loop.md").read_text()
        assert f"turns (default {THREAT_ETA_WINDOW})" in text
        assert f"threat_radius` (default {THREAT_RADIUS_2DP})" in text

    def test_own_planet_classification_defaults_match_params(self):
        text = (WIKI / "Game-Loop.md").read_text()
        assert (
            f"`ships >= fortress_min_ships` ({FORTRESS_MIN_SHIPS}) AND "
            f"`production >= fortress_min_production` ({FORTRESS_MIN_PRODUCTION})"
        ) in text
        assert f"`production >= factory_min_production` ({FACTORY_MIN_PRODUCTION})" in text

    def test_threat_handling_reinforce_fraction_matches_params(self):
        text = (WIKI / "Game-Loop.md").read_text()
        assert f"`defense_reinforce_fraction` ({DEFENSE_REINFORCE_PCT})" in text

    def test_key_parameters_table_matches_params(self):
        text = (WIKI / "Game-Loop.md").read_text()
        assert f"| `threat_eta_window`      | {THREAT_ETA_WINDOW}      |" in text
        assert f"| `threat_radius`          | {THREAT_RADIUS_2DP}    |" in text


class TestDecisionTraceDoc:
    def test_fortress_min_ships_default_matches_params(self):
        text = (WIKI / "Decision-Trace.md").read_text()
        assert f"default is {FORTRESS_MIN_SHIPS}" in text

    def test_factory_min_production_default_matches_params(self):
        text = (WIKI / "Decision-Trace.md").read_text()
        assert f"factory_min_production ({FACTORY_MIN_PRODUCTION})" in text
